name: Run storage script and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run store_data.py on sample data
        run: |
          python3 scripts/store_data.py --json-in data/sample_items.json --db test.db

      - name: Run tests
        run: |
          pytest -q
